//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_GunGrab : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Test_Grab
        {
            get
            {
                return SteamVR_Actions.gunGrab_Test_Grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean Shoot
        {
            get
            {
                return SteamVR_Actions.gunGrab_Shoot;
            }
        }
        
        public virtual SteamVR_Action_Boolean Reload
        {
            get
            {
                return SteamVR_Actions.gunGrab_Reload;
            }
        }
        
        public virtual SteamVR_Action_Boolean EndGame
        {
            get
            {
                return SteamVR_Actions.gunGrab_EndGame;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.gunGrab_Haptic;
            }
        }
    }
}
